package org.crd.carrental.repository;

import org.crd.carrental.model.Car;
import org.crd.carrental.model.Reservation;

import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicLong;

/**
 * In-memory {@link ReservationRegistry}. Thread-safe on its own:
 * {@code reservationsTable} and {@code indexByCarId} are backed by
 * {@link ConcurrentHashMap}, the index's list values are
 * {@link CopyOnWriteArrayList}, and reads return a defensive copy.
 * Reservation ids are generated by a shared {@link AtomicLong}, so they
 * stay unique regardless of any external locking.
 */
public class InMemoryReservationRegistry implements ReservationRegistry {


    private final Map<Long, Reservation> reservationTable = new ConcurrentHashMap<>();
    private final Map<String, List<Reservation>> indexByCarId = new ConcurrentHashMap<>();
    private final AtomicLong idSequence = new AtomicLong(0);

    @Override
    public Reservation create(Car car, LocalDateTime startDateTime, LocalDateTime endDateTime) {
        Objects.requireNonNull(car, "reservation cannot be null");
        Objects.requireNonNull(startDateTime, "startDateTime cannot be null");
        Objects.requireNonNull(endDateTime, "endDateTime cannot be null");
        if (!startDateTime.isBefore(endDateTime)) {
            throw new IllegalArgumentException(
                    "startDateTime (" + startDateTime + ") must be before endDateTime (" + endDateTime + ")");
        }
        Reservation reservation = new Reservation(idSequence.incrementAndGet(),
                car.carId(), car.type(), startDateTime, endDateTime);
        reservationTable.put(reservation.reservationId(), reservation);
        indexByCarId.computeIfAbsent(car.carId(), k -> new CopyOnWriteArrayList<>()).add(reservation);
        return reservation;
    }

    @Override
    public Optional<Reservation> findById(long reservationId) {
        return Optional.ofNullable(reservationTable.get(reservationId));
    }

    @Override
    public List<Reservation> findByCarId(String carId) {
        Objects.requireNonNull(carId, "carId cannot be null");
        return List.copyOf(indexByCarId.getOrDefault(carId, List.of()));
    }
}
